# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('DateOfBirth', models.DateField(default=datetime.datetime(2016, 7, 25, 11, 25, 24, 746442, tzinfo=utc))),
                ('Mail', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=20)),
                ('Organisation', models.CharField(max_length=500)),
                ('Address', models.TextField()),
                ('FromDate', models.DateField(default=datetime.datetime(2016, 7, 25, 11, 25, 24, 747083, tzinfo=utc))),
                ('ToDate', models.DateField(default=datetime.datetime(2016, 7, 25, 11, 25, 24, 747150, tzinfo=utc))),
                ('VerificationCode', models.CharField(max_length=180)),
                ('ProfilePicture', models.FileField(upload_to='profile/%Y/%m/')),
                ('Certificate', models.FileField(upload_to='certificate/%Y/%m/')),
            ],
        ),
    ]
