# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='DateOfBirth',
            field=models.DateField(default=datetime.datetime(2016, 7, 25, 11, 27, 31, 930431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='FromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ToDate',
            field=models.DateField(),
        ),
    ]
