# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20160725_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='DateOfBirth',
            field=models.DateField(default=datetime.datetime(2016, 7, 25, 13, 16, 58, 429665, tzinfo=utc)),
        ),
    ]
