# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20160725_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='DateOfBirth',
            field=models.DateField(default=datetime.date(2016, 7, 25)),
        ),
    ]
