# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20160725_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ToDate',
            field=models.DateField(default=datetime.date(2016, 7, 25)),
        ),
    ]
